name: Mirror to Public Repo

on:
  push:
    branches:
      - fix/full  # Trigger when pushing to fix/full branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Public Repo
        run: |
          git remote add public https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/Varun-ai07/COVENANT.git
          git push public fix/full:full_fixes --force
